# Generated by Django 5.2.4 on 2025-07-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_installed', models.BooleanField(default=False)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
            ],
        ),
    ]
